name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-features
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: rust-clippy-check
  #     uses: actions-rs/clippy-check@v1.0.7
  #     with:
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       args: --all-features
  # perf:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: cargo-bloat
  #     uses: orf/cargo-bloat-action@v1
  #     with:
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       args: --all-features
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
